[build]
  command = "next build"
  functions = "netlify/functions"
  publish = ".next"
  ignore = "bash ./netlify-ignore.sh"

[[context.deploy-preview.plugins]]
  package = "./plugins/create-dynamodb-table"
